module.exports = {
  content: ["./*.html", "./pages/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c9c4d7",
        "tertiary-fixed": "#ffdbc8",
        "primary-fixed-dim": "#cabeff",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "error-container": "#ffdad6",
        "surface-container": "#eaedff",
        "inverse-on-surface": "#eef0ff",
        "on-surface": "#131b2e",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-container": "#5c647a",
        "secondary": "#565e74",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb68b",
        "secondary-container": "#dae2fd",
        "inverse-surface": "#283044",
        "on-primary-container": "#d8ceff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#321300",
        "on-primary-fixed-variant": "#4723be",
        "on-error-container": "#93000a",
        "tertiary": "#713300",
        "primary-fixed": "#e6deff",
        "on-tertiary-fixed-variant": "#743400",
        "surface-tint": "#6042d6",
        "surface-dim": "#d2d9f4",
        "tertiary-container": "#954500",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-container": "#ffc9ab",
        "surface-container-highest": "#dae2fd",
        "on-surface-variant": "#484554",
        "secondary-fixed": "#dae2fd",
        "outline": "#797586",
        "surface-container-high": "#e2e7ff",
        "primary": "#451ebb",
        "surface": "#faf8ff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-primary": "#cabeff",
        "background": "#faf8ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#5d3fd3",
        "on-primary-fixed": "#1c0062",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
